### ISSUE TITLE
Request Handler and Channel Manager Errors

### ISSUE THREAD

**Issue by ThePowerSquirrel** [snappiee/Donkzz#20]
![Screenshot 2024-05-18 163259](https://github.com/snappiee/Donkzz/assets/170210171/b5b9ce29-f2f2-4936-aea8-cbbdf20c1c25)
Don't know how to fix it. Any help would be appreciated.

**Comment by VillainsRule** [comment]
you probably need to join a server dank memer is in

**Comment by ThePowerSquirrel** [comment]
I am in a server dank memer is in

**Comment by snappiee** [comment]
delete, downgrade and reinstall another version LOWER THAN your currently installed discord version, that should fix (if DOWNGRADE isn't good try UPGRADE IT LMFAO) CHANGE THE VERSION PLS
