### ISSUE TITLE
New commands

### ISSUE THREAD

**Issue by Adharsh26** [snappiee/Donkzz#21]
When will trivia, fishing, pet care be implemented? . Love this btw.

**Comment by VillainsRule** [comment]
trivia isn't here? @snappiee selling....

**Comment by Adharsh26** [comment]
> trivia isn't here? @snappiee selling....

Selling Donkzz?

**Comment by VillainsRule** [comment]
no wtf lol it's slang

**Comment by snappiee** [comment]
never get implemented, as nobody had their time doing it also, for just a j4f bot. tysm for being with us
